# -*- coding: utf-8 -*-
"""División de complejos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19P2jNAlFVOKnKFdelWiqBCsgA0HqVoKa
"""

z1 = complex(input('Da un número complejo: '))
z2 = complex(input('Dame otro número complejo: '))
print(z1+z2)
print(z1-z2)
print(z1*z2)
print(z1/z2)

#a = z1.real
#b = z1.imag
#c = z2.real
#d = z2.imag

import numpy as np
from scipy.linalg import solve
AA = np.array([[z2.real,-z2.imag], [z2.imag,z2.real]])
BB = np.array([z1.real,z1.imag])
x = solve(AA,BB)
print("La solución del sistema es: ", x)
#print(a*c - b*d)
#print(a*d + b*c)