# -*- coding: utf-8 -*-
"""Leibniz_valor de pi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eT-op4qY0_Ivek7lfXQjJ07m-8tqCbLN
"""

import numpy as np
z=[]
aprox = 0
for n in range(1,1000000):

      aprox = aprox+ (-1)**(n+1)*(2*n-1)**(-1)
      z.append(aprox)
print(f'{n:>7}{4*aprox:>18.15f}')