# -*- coding: utf-8 -*-
"""limites.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8KAUjyIUpVbQx2MQFILnL6XXhCvQvsG
"""

from sympy import symbols, limit, sin
x = symbols('x')
limit(sin(x)/x, x, 4)

from sympy import symbols, limit, sin, pi
x = symbols('x')
limit(1-2*sin(x)/(pi - 6*x), x, pi/6)