# -*- coding: utf-8 -*-
"""MCD General.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Y4Vy8_bqz7VXcA2SBgIINHhy1B8BHi1
"""

while True:
  a = int(input("Dame el primer entero: "))
  b = int(input("Dame el segundo entero:"))
  if a > 0 and b >0:
    break
  print(" Ambos números deben ser mayores a 0 ")

q = a//b
r = a - b*q
while r !=0 :
  a = b
  b = r
  q = a//b
  r = a - b*q
print("El máximo común divisor es: ", b)